(ns bioclj.t-core
  (:use midje.sweet)
  (:require [bioclj.core :as core]))

(facts permute-domain
       (fact "Permuting strings works"
             (core/combinate-domain "AC" 2) => '((\A \A) (\A \C) (\C \A) (\C \C)))

       (fact "Permuting arrays works"
             (core/combinate-domain [\A \B] 2) => '((\A \A) (\A \B) (\B \A) (\B \B))))

(facts kmer-frequency
       (fact "counting kmers works for a 1-mers"
             (let [freq (core/kmer-frequency 1 "ABCDCD")]
               (freq "D") => 2
               (freq "C") => 2
               (freq "A") => 1))

       (fact "counting kmers works for a 2-mers"
             (let [freq (core/kmer-frequency 2 "ABCDCD")]
               (freq "DC") => 1
               (freq "CD") => 2
               (freq "AB") => 1)))

(facts sorted-freq-kmer
       (fact "sorting kmers ma
       s works for short kmers maps"
             (let [dataset "GTACTCAAGGCTAATAGTCGCTAATAGTCGCTAATAGTCGCCTCTGTCCGCTAATAGTCACAGATTCACAGATTCGCTAATAGTCGTACTCAAGACAGATTCGCCTCTGTCCGTACTCAAGGCTAATAGTCACAGATTCGCTAATAGTCGTACTCAAGTCGGAGTAAAGCCTCTGTCCGCTAATAGTCACAGATTCACAGATTCTCGGAGTAAAGCCTCTGTCCGCTAATAGTCGTACTCAAGTCGGAGTAAATCGGAGTAAAGCCTCTGTCCTCGGAGTAAAGTACTCAAGACAGATTCGCCTCTGTCCGCCTCTGTCCGTACTCAAGGCCTCTGTCCGCCTCTGTCCTCGGAGTAAAGTACTCAAGTCGGAGTAAAACAGATTCGTACTCAAGACAGATTCTCGGAGTAAAGCCTCTGTCCACAGATTCACAGATTCGTACTCAAGACAGATTCGCCTCTGTCCGCCTCTGTCCACAGATTCGCTAATAGTCTCGGAGTAAAGCCTCTGTCCGCTAATAGTCTCGGAGTAAAGCCTCTGTCCGCTAATAGTCACAGATTCGTACTCAAGGTACTCAAGACAGATTCGTACTCAAGTCGGAGTAAAGCCTCTGTCCTCGGAGTAAAGTACTCAAGTCGGAGTAAAGCTAATAGTCTCGGAGTAAAGCCTCTGTCCGCTAATAGTCGTACTCAAGACAGATTCTCGGAGTAAAGTACTCAAGTCGGAGTAAAGTACTCAAGGCCTCTGTCCTCGGAGTAAATCGGAGTAAAGTACTCAAGGCCTCTGTCCGTACTCAAGGCTAATAGTCGCCTCTGTCCACAGATTCTCGGAGTAAAGCTAATAGTCGTACTCAAGACAGATTCGCTAATAGTCGCCTCTGTCCGCCTCTGTCC"
                   freqmap (core/sorted-freq-kmer {"CCGCCTCTGTCCGT" 8, "GAGTAAAACAGATT" 1, "TAAAGTACTCAAGT" 3, "ATAGTCACAGATTC" 4, "CACAGATTCGTACT" 2, "TAAAGCCTCTGTCC" 8})
                   results (core/sorted-freq-kmer (core/kmer-frequency 14 dataset))]

               (first freqmap) => ["TAAAGCCTCTGTCC" 8]
               (second freqmap) => ["CCGCCTCTGTCCGT" 8]
               (first results) => ["TCGGAGTAAAGCCT" 8]
               (second results) => ["TAAAGCCTCTGTCC" 8])))

(facts kmer-indices
       (fact "returns a hashmap with vectors containing the indices substrings are found"
             (let [freq (core/kmer-indices 2 "ABCDCD")]
               (freq "DC") => [3]
               (freq "CD") => [2 4]
               (freq "AB") => [0])))

(facts kmer-clumps
       (fact "returns a list of keys for values in a kmer-indices result which have n+ matches, within L chars"
             (let [freq ()])
             ))

(facts reverse-complement
       (fact "returns the reverse complement of a strand of nucleotides, regardless of whether it's in upper/lower case."
             (let [strand "TCGGAGTAAAGCCT"
                   strand2 "TcgGAgtAaaGcCT"]
               (core/reverse-complement strand) => "AGGCTTTACTCCGA"
               (core/reverse-complement strand2) => "AGGCTTTACTCCGA")))

(facts hamming-distance
       (fact "returns the number of mismatches in two equally sized strings"
             (let [s1 "ACTG"
                   s2 "AATG"
                   s3 "ACTGA"]
               (core/hamming-distance s1 s1) => 0
               (core/hamming-distance s1 s2) => 1
               (core/hamming-distance s1 s1 :d 0) => 0
               (core/hamming-distance s1 s2 :d 0) => 1
               (core/hamming-distance s1 s1 :d 0 :dmax 0) => 1
               )))

(facts neighborhood-recur)
;; why the $#@! is this wrong??!/!/!/!?? lulz

(facts transcribe-rna
       (fact "transcribes RNA into a peptide chain"
             (let [rna "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA"
                   peptide "MAMAPRTEINSTRING*"]
               (core/transcribe-rna rna) => peptide))
       (fact "also works with DNA"
             (let [dna "ATGGCCATGGCGCCCAGAACTGAGATCAATAGTACCCGTATTAACGGGTGA"
                   peptide "MAMAPRTEINSTRING*"]
               (core/transcribe-rna dna) => peptide))
       (fact "probably blows up if the RNA chain isn't a multiple of 3"))

(facts rna-encodes-peptide?
       (fact "if the RNA strand encodes the given pepide"
             (let [rna1 "ATGGCC"
                   rna2 "ATGGCC"
                   rna3 "ATGGAT"
                   rna4 "GATATG"
                   peptide "MA"]
               (core/rna-encodes-peptide? rna1 peptide) => true
               (core/rna-encodes-peptide? rna2 peptide) => true
               (core/rna-encodes-peptide? rna3 peptide) => false
               (core/rna-encodes-peptide? rna4 peptide) => false))
       (fact "stops as early as possible"))

(facts find-encoded-peptides
       (fact "finds encoded peptides in both the forward and reverse compliments of an RNA strand"
             (let [rna "ATGGCCATGGCCCCCAGAACTGAGATCAATAGTACCCGTATTAACGGGTGA"
                   peptide "MA"
                   strands (sort '("ATGGCC" "GGCCAT" "ATGGCC"))
                   rna2 "TTCGAATCCGTATTGCTTTGGTTGGTTGAGAGAGCGACCTACATTGCTAGTCAGAATAGGTGATTCACACAAAGCTTAGCACCTGGGCAGCACCCCGTGATGTAAACCTATGGGAACTAAGGGAGTCCTGCGGTTTTAGCCAGCAAGCGAGCCGGCAGGAACACTCATACCATCGGACGCGTTTGACGCCTCCCCGGAAAGGAAGTATTTGAGCCTCATTATTACGTATTGCCCGTTAGTCGACAAATCAAGCCCTCGTACGCAGCTTATTCGTACGACGTGGAGGCGTTCCCACGGGCCTAACACGATTGGAACACCACCATAGTAGTGTGGTTCAAATACCTCCTTTGGAGATCTAGAGCTTCACTCTGATTCTAGAGGCAACTTTACAATCGCTCTACGAAATTGTATGGACATCATCAACCGGATATTCTGGGGCGGTAGAATTTCTTTTGTTCGAATCGCTCTAGGCCAGGATCAAATTAATTGAATTGCGGACTCAAGGATCGCGATAGCCGACACATCGGACGCTGTAGAAAGCCAGTCTCTGGATTTAATCCACCCTCTATGTTTGACAAAGCACTAAAACGGGATAGTTTCGGGTGGTATAAGTTTCCCAAGACGATTGCATCGCAATTCATCAACAACCATGAACTTACTGTTTTAGTACTTCCACACACCTTGTTAAATTACGCCTTTACTTCATGTTGCGGTGTGTGTTAGATAGTGTGCAGCTACAAGTCTACCGCCATCGCAGCTCGGGATACCGGCAGATGAGATGGTCCTGAGCTCGTACCGGACTCAAACTTTTTCCTTTACTACCTAGGAATCGCCCATGCGAATTTGTCGGACACACACCATTACATTAACGTCACAACAGCTACTGTTAGAATTTTGCTCTTGCAAATCCTGGAAAGAGTTAAAAAAACTCTTCCGCGCGCCAATAGGGTAAATAATAGATAGCCAGACGGCTGTAAGAGGTGATGACATTTGCAACAATCATGCTGTCGCATCTTCCGCAAGTTCATGTCGCGCCTAGGCAATGGATCTGCGAATGGGGGCCACGGGGTATGAACTACGGAATTCTAAGAAAGTTGCCATCCAGAGTTAAGGGTTTGAGGCTAGTTGCATCGCTGGTAACGAACTACCTCATTACTTGGACGCGCAGTGTGACTTCACTCCTGTATAGCGATGATGCCAAGCAGGAATTAGCAAATCTGAAGAGCGTTTCCAAACTGGCCACTTGGACTGACACCTATCGCGGGGGATTTCAGCGCGTGTCGCTCTCACATGAGAGCTGCCGTCAGGAGCGGTAGAGTTTAGAGAGGAATGCGACAAACTCCCTATTCACCTCTCTGGTGATGTAAGGATATTTACGCTTAGTTCTATGCCAGGCTTAGGGCCTCTCGGAACTTTGGTGAGTCCTTATTAATTGATGCTACCTCTCCCTTACCTTCGCCCCAAGTCACGTAGAAGTACTCAATCCTGCTACATGATAATCAAATATTTCCAACGTTGGGAAATCGGTGACATCACATACTAGTTAAGAAACCACTGTCAGTGAACTTATATCCGGGGGAGAAAATCTACTAACTTACATACGCTGTGCGAGCAGTTTTCATTATAAGAAAATATACTCCCGAGGTACCGCATCAAGCACGACATTCCCGGAGAGCATAACATTTCGGTGCACCTGCTTTTGTGCGCTTGCTTGCGGTTATTTATAAACTACGCACAAGGCGCAAACCGCAGTGCGCATGTTTTCTCCGCCTGGCTAGAACTCGACATTCTCGTCAACGCCAATCTATGTGAGAGGATTTAGACCTCTGTGAAAACGAGTCCCTCTATAGAATAAATACCCAGATGCCAATGGGGGTTCTATCCGATGGCAGTGCATGGAGTGGTGGCTCCAGATTAAGGATGAGGAGAGGTAAAGATAACAGTTCGGTCGCCACGACGCGTTGCCAATCGAAATATCAGTACTAAAAGGCCCACCGCTCCGCTTTAGTCCGACTTTACATCCTGTGGAAATTGTCGAACGGAGGCTACATCGGGCTATATGAGTGTGAAAACCTATACTTCTCGCGTCGTTACTCAGTGCCGGTCTCCTGTTTCCCCCAGTCTTACGTACCCTTATTGATATTTGCTTCACGTTGAAACGTCCTAACGCAGCGTAAAGAGGTGTTTGAACCTCATTACTATAAAATCGCGATCGAAGGTAGACTACATACGCAAACGCCGAAACCCTCAGTTGGCCTTGTTGCAAGTATGGAACGTTGTAAAATTTTTCCTAGACGTTGAGCTATCGGTACAAGGTCGTTAGCGTCCTTACCCTTCACTTATATGCCCGACAAAACGCGGGTCCTAGTGCAGTGGTGGGAGCTTGGAATCCCGCAATACAAGGACAACCTGTATCTCGTTCGGCGTTCCGCGATCACTCGATCCCGAACCACTCCAAGCCTGGTTGATCAGCAAAAGCGGAAGGATGGATAAAGGGCTACTGGTTAATGGATGTAAACTTCCAATGATGAAATCCTGGAAACGAGGGATCGGGTTACGGTGGCGAACGGGGTACGGCAACGTGGCTATCTAGAGCCCGACGTTACGACTCATGTACATGCTGCTACGTGGTTGAAGCTGACGTTCAGATGAAGCAGTACTGAGTCCTAGGGCTTACTACTACTCCAATAGGTCTGGCCGGCCAGATACAAAAGTTCGTGGCGGCTCACCCCCTTTCTGGCGGGTGTAGCTTGCTGACCGGTTTGCTCGATAACACAGGCTAGCGAATAGTAATGAGGTTCGAAAACCTCTTTCCAACGACTGAAAGGGTCTACACGAACTATCTACATTTCCCCGCCCATGTCCTTCCGTCTGGTTGCTTCTGGAGATCCTTTCGCATTATACCGCAGCGTAGTGGCTCTGGCATATATGAAAAAATCCTTCTGTGGGTATTTGTGCCATCACTTATTGTTCGTACCGATATGGGATTACAAGTGCGATGTGATAATAAGCGAAGAAGCCAACATGTTACACTGTTCATGCGCTCCGGGTAATGTGCGGGCACCATGCTCAGTTCCCGCTCGCAGTTGTCACTGTCCCTGTTTCGGCACCATAATCAACATTTCCACGGCCACGCTGGTGAATAACCGAGGATACCGAAGTACAGCAAGAATGAGAGCGGGACTCCTCCATCTGCTTGTAATACGCCTTCAAGATAGTCCATAAAACGGTCGGGGTCTTGTTTCGGACTAGCCGCTTTGAAACGGTGCATAGTTGTGTCAAGTGTGGACATTGGCTTTCTATCCTCGTCAGCGATCCTCGGAAAGACTCGGGCAGTCGCCCCGAATCGTAATTAGGTAGTAGTGCGGCTCAAAAACTTCCTTCGACCTAACCGCTATAATGTTCGTAGATATAAATTTCGTTTCAGTATTAACAGGCGCACCGTATATATACGGAATGGTGTCGCCCCATTAGCTGCTCGCCAATATTTATCTAAGACCGCGCGCGTCTAGCGCCTTTAGTAGTTGCACCCGAGTATAGTAATGGGGTTCGAAGACTTCCTTCGCAAGGCTGCCATACTGTATCACAAGTACTGACGGAGCCCCGGAGGAGTGCAGGATACGGCAAAGGAGACCATTACCGGGGCATGAGTCCAAGTTAGCCCGTTAGGTGAAGGACGCTGATACAATAGTGAATCCGTTACTGAAAGGTTTAGAAGACCGGGGGGCTCGCACTAGGTCCAAATATTATGAACCCTACTCCTGCAACTGAATTGGCCGTCCAGGCGATATTTAAAAGGGGTTACTAGCAGGTTCATCGGAGCCCGTACTCCTTCCGGGCATAGTCGTTCGACGGGTAGAAATTCATCCAGTCGTGCCGGATACCCCGAGAATACCCCTATTTTTTGATCCTTCACCATCATCGTCCGCGGACTCATCTAAGTACCTCAGACCGAAACTGTTATCGTAGCGAAGAGCGAACTCGAATGACATCGCTTGTCCAACAGGGAAAATATGTAAAGTATATGCAGATTATTATAGGAAGATCACAAACTCCATCGCGCCTAGGCCAAAGACTTGCCAGAACAACATCTCTTCCAGAGCAAGGAAGTGTTTGAACCTCACTATTATCGAGAGAAGTCCCATGAATTTATAATAGTGAGGCTCAAAAACTTCCTTCATCGTCGGGCGCTGGGGCGAGCTAGGCTTCCCTAGCCGTCATTACTGTACCCACGCCAAATATTATCGAGTATGACTACGAAGCCTTCACAAGGGGCTGCAGTAACAGACTAACTCACGCACACCGCAACTACTATCCTAAATTGAGTAAGAAAACCCTCGACTATAGCCCTTGAATTAAATTCGCTATTTAAGGAAGACCGCGCTTCCGCTCGCCCGCGTATAGTTTACCAGTCCCAAGAAACATGTGTGGCCAGCCTACCTGAAGAGCTGTGTAAAGATAGATTCTGACATCCTCAAAAAGAAGTTTTCGAGCCGCACTACTACGCACGGAGCTCCGTTATTCAAGGCATGTCGAAGTACAGCGTGGTGGCCTCTCCTGTTCTCCACCCCAGCTAAACCCACCTTGTTCGAATTCGCGCAACTGTATATGACATGAACACTTACAGGGGTTAGAAGTTACTGCAACCAAGATAGAGCTCGTCGAAGTAATAGTGCGGTTCAAAAACTTCCTTCAATTGGTCTCATCACTTAAATTTAAGAGCTATTGTGAGTACAGGTACGGATGCGGCTTCAGTGGATCTTCAGCATTCATTCCTTGTAGTAATGGGGTTCGAAGACTTCCTTGCCAGGGTACCAAACAAGTCTTGCGCATCCTCCTCCCTAAGGAGGTATTTGAACCCCACTATTACCCACGATAGAACATGCAGGGTTTGATAGTGGAACACCTTTTAGAATCTGGGGATAAATTCCCAGGACTAATGTATGGCTGTAGTAATGAGGTTCAAAAACCTCCTTTTCAGGTGGATCGCAGGCCGTGCTGCCTCACAAGCTGGGACGCCGTCCACGGTATAGCCGGCGTCGGCAGTTACTGTGAAATAGCGGAAACTCGATCCCAATATATCATCTTACGTTTGGCGCCCAATAGTCGCCCAGTACCCGTTGACAGTTCTTTAACTCGGCTTAGAACTACTAGACAGGTTCAACCGAACCTTGCCCTAGTTCCCACTCCCGTAATTCATTTGGGTTTGCATCTAGAATACTGGAGGGTGCATAGACGAAACGTGTACGTCGGAGAAAACGTAAGAAAATGACCTAGACTCATAGTAGTGAGGTTCGAAGACTTCCTTTCAGTGAAATCGATCCACCACTCGCCGCGAAGAGATAATAGCATAGAGCACAAGTGCGCGAGTAGAGAAAAAGGCTATCCCAACCGGGCACGTCCTTCGTGTTTGGCGTTTACATACGGCACCCCGTTTCTGCACGTTAACCGTCTAGTATCCAACGGTGGATGGCGGACGCTAGACTATAGATATGAGATATCGAGACCTGGAGCTGGGTGTGGCTGCAGCCCGGGTCATTGCGGGCTGTGAATTCAAGGGCATGTAAACAAGCGTATATCGAACAGTGGATGGGCACCTGCAATACTCACGGTAGAGTTAGCTCACAGGATTCACGTTGAGGACTATGAGTCCCTCTTCGCTAGCAGTCTGGGGGGATATGGAGTTTAATAGCTTGACGTAGTAATGGGGCTCAAACACCTCTTTGTGTGAGCACAGCTACTTGCATTAAGAGATTCTAAACAGCGATCATCTCGGCTATTTCGGGCCAGCCTTTTCGGCAGGATGTTATGTAGCATTTCTGGAAGCTTCCCCCTCGAATCTACTAGTGGTGAGAAGATGCCCCACCGATATTACTCTTTAATCTTGAGAAACCTAAAACCGATCTGACCTCAGACGGGCGGCTCCCACCCGAGGATAAACTCGTCAATAATAATGTGGCTCGAACACTTCTTTTCTCACTAGGCTTTTACGACACGCCACATGTATTTAAGCATCTACCTAACTTGTGTCTGCTGATATACAGCGCATTCTACGCCCAACCTACCAATTACTTCAACGTAGTGCGTGGCTAAAATTCAGGGGAGCTTCATCTCTGTCTTAATTTGAAGGTTCTTCCGGGGCGTTTGGGAATCTTCGTGCCTTTTGCGAGGTTAAGGTATCAAAGAAGTTTTCGAACCACATTATTACCGCCTTAAGCACCGGCGCATCCTGCTCGTGACAACTCTACCCTGCCCTGATAAAGGCACTGAACGTTCCAGAGAGTGCATCATTGACACGCGAGCAGGCCACAGTAGCCACAAGACGTATGGGTGATTATAGAATTGGTGGAGGTGTTGTTAACGATCAGGAGGACATTAGTGGGAGTTAGGAAAGACCCTATGTTCTCTCTATCGCGGACTTGTAACTTGACAAGCAAAAGGGTAAGAGAGCTGCACACCGAAGCAGGCCCTTCCTATACCTGTTTTTCCTACGCGTAGAGAGGAATCCAGAAAGGTGATAATTGGCATTCGATGAAAAAACAGTGTGCCACTGACTTAGTTCTATATGTGAAGAGCCTGTTAGCACGTGACGGCGGCCTTGGTATAGAGCCCTTAATGGTCTCCATCGCGTAGTAATGGGGCTCGAAAACCTCCTTACTTGGGATTGCGTGGCCTCCTTGTGAGTCATACACAAGGCTTAGGGCTATGGGGCGATACACTCCTTTTCGCGGCGCATGGGGCGGTGATGCCTACATAGTAGTAGTGACTGCCTTTCTGGGGGGCTATTTGTGGATGACCAACACCTGACCAGCGATGCAATCGCTAGGGGAGGTACACCTCTCATATGTTACAACAATCACCGAATTGTGTTTCGAATTCGAATCAAGTTTGCGGTGTCGACCAGATCTGGTCTTGCTGCCATACCGGGTTCGCCGCCTCCGGTGGATAGAACTGCATCTTAAGACATCTGGACCCAGCGGTAAGTAGCGGGAAGAGTTTAGAGTCATTCGTACAACTACAGGCTAAGGGCTTACTGGGGAGTTGTTGTAGGGCATAAAGATCGCCCCATGACTTTTCGTACTTTCCCCGATAGTTCACTCGCAGCGAGCTGCGGCTGGGCTTCGCCACACGAGTACGGGCAACATTTATCTCCTCTAATCACTGGGCACCGCGCGAGGAAATAGAAAACCCTAATCAGTGCTCATGGGCGCATCTATTGGTCTCCGCATGCACGATGCCGCGGAGTGCTTAGTTGTCCCTGCATAATCTTCGTAGATGTATAAGAGATTACCTATTTATTCGGTTTCGGTTCTAGACGTACCTTGCCGCATGAGTATAGGCTAATGAACTGAGTTGGCGCCAGAGGGAAAGGCATAATAATGCGGCTCGAATACTTCCTTAAGGAAGTATTCGAACCACATTACTAT"
                   peptide2 "KEVFEPHYY"
                   strands2 (sort '("AAGGAAGTATTTGAGCCTCATTATTAC"
                                    "AAAGAGGTGTTTGAACCTCATTACTAT"
                                    "AAGGAGGTATTTGAACCCCACTATTAC"
                                    "AAAGAAGTTTTCGAACCACATTATTAC"
                                    "AAGGAAGTGTTTGAACCTCACTATTAT"
                                    "AAAGAAGTTTTCGAGCCGCACTACTAC"
                                    "AAGGAAGTATTCGAACCACATTACTAT"
                                    "ATAATAATGCGGCTCGAATACTTCCTT"
                                    "GTAGTAATGGGGCTCGAAAACCTCCTT"
                                    "GTAGTAATGAGGTTCAAAAACCTCCTT"
                                    "GTAGTAATGGGGTTCGAAGACTTCCTT"
                                    "ATAATAGTGAGGCTCAAAAACTTCCTT"
                                    "ATAGTAATGGGGTTCGAAGACTTCCTT"
                                    "GTAGTAGTGCGGCTCAAAAACTTCCTT"
                                    "ATAGTAATGAGGTTCGAAAACCTCTTT"
                                    "ATAATAATGTGGCTCGAACACTTCTTT"
                                    "GTAGTAATGGGGCTCAAACACCTCTTT"
                                    "ATAGTAGTGAGGTTCGAAGACTTCCTT"
                                    "GTAATAGTGCGGTTCAAAAACTTCCTT"
                                    "ATAGTAGTGTGGTTCAAATACCTCCTT"))]

               ; $#!@ if i know, that example's wrong!
               ;(sort (core/format-encoded-peptides (core/find-encoded-peptides rna peptide))) => strands
               (sort (core/format-encoded-peptides (core/find-encoded-peptides rna2 peptide2))) => strands2
               )))

(facts linear-subpeptides
       (fact "returns the set of possible subpeptides, given a linear peptide"
             (let [peptide "ABCD"
                   subpeptides '("" "A" "AB" "ABC" "ABCD" "B" "BC" "BCD" "C" "CD" "D")
                   actual (core/linear-subpeptides peptide)]
               (sort actual) => (sort subpeptides)
               (count actual) => (count subpeptides))))

(facts cyclic-subpeptides
       (fact "returns the set of possible subpeptides, given a cyclic peptide"
             ;; TODO: fix so complete protein configurations are only completed once
             (let [peptide "ABCD"
                   subpeptides '("" "A" "AB" "CDA" "ABC" "DA" "ABCD" "B" "BC" "DAB" "BCD" "C" "CD" "D")
                   actual (core/cyclic-subpeptides peptide)]
               (sort actual) => (sort subpeptides)
               (count actual) => (count subpeptides))))

(facts peptide-mass
       (fact "sums each amino acid's mass in daltons"
             (core/peptide-mass "CANCER") => 676))

(facts linear-subpeptide-masses
       (fact "maps the mass sums for each linear subpeptide"
             (let [peptide "LYFE"
                   actual (core/linear-subpeptide-masses peptide)
                   actual-max (apply max actual)]
               (count actual) => 11
               (sort actual) => (sort '(0 113 129 147 163 276 276 310 423 439 552))
               (count (filter #(= %1 actual-max) actual)) => 1)))

(facts cyclic-subpeptide-masses
       (let [peptide "LYFE"
             peptide-masses [113 163 147 129]
             expected (sort '(0 113 129 147 163 242 276 276 310 389 405 423 439 552))
             actual (core/cyclic-subpeptide-masses peptide)
             actual-max (apply max actual)]
         (fact "maps the mass sums for each cyclic subpeptide"
               (count actual) => 14
               (sort actual) => expected)
         (fact "only count the completely peptide configurations once"
               (count (filter #(= %1 actual-max) actual)) => 1) ;(count peptide)
         (fact "also works when run on a collection of integers, though excludes possibilities with duplicate amino masses"
               (core/cyclic-subpeptide-masses peptide-masses) => expected
               )))

(facts expand-peptides
       (fact "expands peptides by adding each possible amino acid mass to the enumeration, returning a list of vectors"
             (let [peptides [[123]]
                   expected (map (fn [i] [123 i]) core/int-mass-values)]
               (core/expand-peptides peptides) => expected
               )))

(facts consistent-spectra
       (let [actual-spectra-freq (core/spectra-count (core/cyclic-subpeptide-masses "CANCER"))
             spectra1 '(71 129 288)
             spectra2 '(71 129 288 288)
             spectra3 '(71 129 288 288 288)
             spectra4 '(71 129 300)]
         (fact "spectra are consistent which include one each of the masses"
               (core/consistent-spectra spectra1 actual-spectra-freq) => true)
         (fact "spectra are consistent which include up to count of the actual spectra"
               (core/consistent-spectra spectra2 actual-spectra-freq) => true)
         (fact "spectra are inconsistent when they include more than the count of the actual spectra"
               (core/consistent-spectra spectra3 actual-spectra-freq) => false)
         (fact "spectra are inconsistent when they include frequencies not in the actual spectra"
               (core/consistent-spectra spectra4 actual-spectra-freq) => false)))

